spring.datasource.url=jdbc:mysql://localhost:3306/course_db
spring.datasource.username=root
spring.datasource.password=RgFyuJxJWNYocZxKSACXtioPmAlYmSNbW

spring.jpa.hibernate.ddl-auto=update
server.port=8080