spring.datasource.url=jdbc:mysql://nozomi.proxy.rlwy.net:10850/railway
spring.datasource.username=root
spring.datasource.password=bRHIXGfPQkgwvwBUcXFIAhxQrpjBLQey

spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}